/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

CREATE DATABASE IF NOT EXISTS `teste_clientes` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `teste_clientes`;

CREATE TABLE IF NOT EXISTS `clientes` (
  `id` int(2) unsigned zerofill NOT NULL AUTO_INCREMENT,
  `nome` varchar(250) DEFAULT NULL,
  `nome_social` varchar(250) DEFAULT NULL,
  `cpf_cnpj` char(20) DEFAULT NULL,
  `rg_ie` char(20) DEFAULT NULL,
  `data_cadastro` date DEFAULT NULL,
  `cep` char(15) DEFAULT NULL,
  `logradouro` char(50) DEFAULT NULL,
  `complemento` char(50) DEFAULT NULL,
  `bairro` char(50) DEFAULT NULL,
  `localidade` char(50) DEFAULT NULL,
  `uf` char(2) DEFAULT NULL,
  `ibge` char(50) DEFAULT NULL,
  `telefone` char(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
